### ISSUE TITLE
Make jQuery.ime work on content editable divs

### ISSUE THREAD

**Issue by santhoshtr** [wikimedia/jquery.ime#136]
Mediawiki extension Narayam has this feature. Need to port that code to jquery.ime

**Comment by ssagari** [comment]
any demo examples will be helpful in this case

**Comment by santhoshtr** [comment]
@ssagari please check the examples folder. https://github.com/wikimedia/jquery.ime/blob/master/examples/ced/ced.html

**Comment by ssagari** [comment]
Thanks Santhoshtr
