### ISSUE TITLE
If contentEditable cursor not in a text node, then insertion goes before the first CE text character

### ISSUE THREAD

**Issue by santhoshtr** [wikimedia/jquery.ime#420]
As per https://phabricator.wikimedia.org/T121216

Steps to reproduce:

1.   Go to the contentEditable div in http://thottingal.in/projects/js/jquery.ime/examples/
2.  Move the cursor to the end of the content, and press Enter to create a new paragraph (actually `<p><br></p>` in most browsers).
3. Enable Malayalam input, and press 'x'

Observe that the text gets inserted at the very start of the contentEditable text, instead of where the cursor is.

This happens because in jquery.ime.js#getDivCaretPosition, traverseTextNodes only checks node === range.startContainer in text nodes. So in the case outlined above, it fails to detect the selection range, and hence the default range of 0-0 is returned.

More generally, the "position" values used by getDivCaretPosition / setDivCaretPosition only count text characters (i.e. code units in text nodes). This would need to change in order to represent offsets that do not lie within a text node. Adding one for each node entry/exit (including of text nodes) would probably solve this. (I predict the use of Node.normalize() etc would not cause problems, because I don't think the offsets need to remain consistent between invocations of the keypress listener).

**Comment by divec** [comment]
https://github.com/divec/jquery.ime/commit/0ab3a252c171069325d391bc352b8ffe45791852 is a start: it seems to work quite well but I'll test it further

**Comment by divec** [comment]
See https://github.com/wikimedia/jquery.ime/pull/422

**Comment by divec** [comment]
Fixed by 65cdfaf44282760cf4e7e8d2f541df8f6a233af3
