### ISSUE TITLE
Urdu IME: Provide a variant of the "صوتی" which uses Latin numerals like "ٹرانسلٹریشن" does

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/jquery.ime#450]
The convention on urwiki (at least) is to use Latin numerals, which is not possible with their favoured (phonetic) IME.

Essentially they'd want https://github.com/wikimedia/jquery.ime/blob/HEAD/rules/ur/ur-phonetic.js but with the definition with [ '1', '۱' ] replaced with [ '1', '1' ] _etc._.

(Reported in person at Wikimania 2016 by User:hindustanilanguage; upstreamed from https://phabricator.wikimedia.org/T138399.)

**Comment by santhoshtr** [comment]
https://phabricator.wikimedia.org/T138399 cosed
