### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by pvnr0082t** [wikimedia/jquery.ime#453]
Hi @santhoshtr @amire80 ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this project in cdnjs.
But I'm not sure which files in this repo need to be added, could you please help up find out the main files?
Or is it possible to provide a `dist` folder for distributed purpose and put main files into it? It will be easy to automatically update for the library in cdnjs.
Thank you.

https://github.com/cdnjs/cdnjs/issues/8979

**Comment by srikanthlogic** [comment]
4 js files under [jquery.ime/tree/master/src](https://github.com/wikimedia/jquery.ime/tree/master/src) and  all the files in [rules](https://github.com/wikimedia/jquery.ime/tree/master/rules) sub folder (except README.md) along with the same structure would be files needed by consumer of this library.

**Comment by pvnr0082t** [comment]
@srikanthlogic Thanks for big help. :facepunch:
