### ISSUE TITLE
Incorrect localized input method name for 'ar-kbd'

### ISSUE THREAD

**Issue by youcha33** [wikimedia/jquery.ime#458]
The localized name for 'ar-kbd' is wrong.

Instead of
> 		'ar-kbd': {
> 			name: 'أرابيك',
> 			source: 'rules/ar/ar-kbd.js'
> 		},

It should be
> 		'ar-kbd': {
> 			name: 'العربية',
> 			source: 'rules/ar/ar-kbd.js'
> 		},

in https://github.com/wikimedia/jquery.ime/blob/master/src/jquery.ime.inputmethods.js#L14

**Comment by kartikm** [comment]
@amire80 Can we verify and fix this?

**Comment by amire80** [comment]
Thanks @youcha33!
