### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by jeblad** [wikimedia/jquery.ime#482]
With a lot of old pull issues, is this repo dead?

**Comment by kartikm** [comment]
Yes. See: https://github.com/wikimedia/jquery.ime/pulls?q=is%3Apr+is%3Aclosed

**Comment by amire80** [comment]
Very much so.

As it often unfortunately happens, we collected a bit of backlog, and @kartikm and I have been addressing it lately.

We'll get to your patches very soon as well :)

**Comment by jeblad** [comment]
Nice! Note that there are some comments on my patches, so check them out before merging.

**Comment by jeblad** [comment]
I have closed my pull requests.
