### ISSUE TITLE
Slant a little to the right in Firefox v57

### ISSUE THREAD

**Issue by asciian** [wikimedia/jquery.ime#504]
In Firefox v57 for macOS, the popup with which we select languages slant to the right. I guess some of style is not active in the Firefox. And I tell you that Google Chrome and Safari is working well and the ime of Wikipedia is working well too. Thank you.

![screen shot 2017-12-12 at 10 59 07](https://user-images.githubusercontent.com/5019902/33863524-8538c114-df2b-11e7-8633-1e17044b8b23.png)

P.S.
I found, on the some of site (http://www.perseus.tufts.edu/hopper/morph?la=latin), the ime isn't working with Google Chrome and my tiny [userscript](https://gist.github.com/asciian/2879c3e7b7720d1a1c665751877e4a64).

**Comment by santhoshtr** [comment]
The positioning code for the IME selector is not solid enough to support all kind of input fields with crazy styles, positioning. That may be the reason. The relevant code for this is at https://github.com/wikimedia/jquery.ime/blob/master/src/jquery.ime.selector.js#L262

Any debugging help here is appreciated.

**Comment by asciian** [comment]
I got it. I'll try to this issue. Thanks for reply!
