### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by bennylin** [wikimedia/jquery.ime#588]
Hi, I'm going to update the transliteration for javanese (/rules/jv/), but it has been 7 years, and I forgot how to test it (new place, new computer, etc.). Could somebody tell me how to test the transliteration script? Thanks.

**Comment by bennylin** [comment]
Help?

**Comment by santhoshtr** [comment]
Please read the documentation at https://github.com/wikimedia/jquery.ime#running

**Comment by bennylin** [comment]
Thanks @santhoshtr
