### ISSUE TITLE
jquery 3.x versions are supported?

### ISSUE THREAD

**Issue by kskarthik** [wikimedia/jquery.ime#693]
The example has v1.x which is oudated, Latest jquery versions are supported?

**Comment by kskarthik** [comment]
It does seem to work with 3.x series of jquery!

**Comment by santhoshtr** [comment]
Yes, it will work with latest jquery.

**Comment by kskarthik** [comment]
@santhoshtr I just made a firefox add-on https://addons.mozilla.org/en-US/firefox/addon/wikimedia-input-tools/

**Comment by santhoshtr** [comment]
That is great. We have a chrome extension too.

**Comment by kskarthik** [comment]
@santhoshtr v0.2 of the add-on is live! This version will toggle between last saved ime & default with Ctrl+M and persistent across all the pages!
